[package]
name = "confilang"
version = "0.1.0"
authors = ["Luka Peschke <mail@lukapeschke.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
clap = "3.0.0-beta.1"
